name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Docker Compose Execute
      run: docker-compose -f "./docker/docker-compose.yml" up -d
    - name: Build Application JAR
      #working directory: .
      run: mvn clean package